### ISSUE TITLE
Book DNS entry for application and add to radixconfig

### ISSUE THREAD

**Issue by nilsml** [equinor/data-marketplace#110]
**In order to make an easy to remember URL for the application, we will register a new dns entry for it**

## Sub-tasks

- [x] Request DNS change in ServiceNow
- [x] Generate csr and request certificate in ServiceNow
- [x] Apply for Azure subscription so that we can add key to keyvault in our own RG
- [ ] Set up radixconfig with dns and certificate
- [ ] Set up keyvault in Azure and store private key

## Acceptance criteria
Application can be reached by _datamarketplace.equinor.com_

## Depends on
- https://github.com/equinor/data-marketplace-internal/issues/2

**Comment by nilsml** [comment]
Everything applied for. Waiting for the tasks to be carried out.
