### ISSUE TITLE
Establish a wiki with information on how we want to work, about the team and their responsibilities

### ISSUE THREAD

**Issue by nilsml** [equinor/data-marketplace#111]
## Todos

- [ ] Team contract (Start Smart perhaps?)
- [x] How we write issues (user stories, problem stories etc)
- [x] How we use the board
- [x] Meetings we should have and who should participate
- [x] Using Git, trunk based or branches, rebase strategy or merge, etc
- [x] How to work with the backlog - prioritizations and such
- [x] Kanban, SCRUM, Scrumban... how do we iterate?

**Comment by nilsml** [comment]
Most stuff added to wiki. Only thing we haven't done is team contract. A nice concept that we might discuss when everyone is back from holidays.

**Comment by aronhoyer** [comment]
what's the reasoning behind the branch naming change suggestion? up until now, the github flow has been followed. as the section intro on branching states: `[feature|hotfix|bug]/[branch-name]` is a relic of git-flow, which is a more involved git workflow with a production branch, development branch (which all feature/hotfix/bug branches branch out of), release candidate branch and feature/hotfix/bug branches.

**Comment by aronhoyer** [comment]
also, what are our choices of wiki? are we stuck choosing between either onenote or github wiki?

**Comment by nilsml** [comment]
> what's the reasoning behind the branch naming change suggestion? up until now, the github flow has been followed. as the section intro on branching states: `[feature|hotfix|bug]/[branch-name]` is a relic of git-flow, which is a more involved git workflow with a production branch, development branch (which all feature/hotfix/bug branches branch out of), release candidate branch and feature/hotfix/bug branches.

I can agree that the feature/hotfix/bug prefix is a bit obsolete, so that part of the wiki we can change. It was just copied from other projects we are running. However having the issue number and shortname in there is something we should do. It is much easier to get the context in a glance following this approach.

**Comment by nilsml** [comment]
> also, what are our choices of wiki? are we stuck choosing between either onenote or github wiki?

I am open to suggestions. I thought you and Ovin chose OneNote. I like Confluence, but seems like I am the only one...

**Comment by aronhoyer** [comment]
> However having the issue number and shortname in there is something we should do.

i can agree with that 😄 

> I thought you and Ovin chose OneNote. I like Confluence, but seems like I am the only one...

ovin convinced me at the time because of the convenience of it, but now i'm finding limitations that get in the way of efficient async teamwork.

i wanna suggest [notion](https://notion.so), but it **can** be a bit iffy to get into.

**Comment by nilsml** [comment]
I did some investigation on Notion. It is allowed to use it seems, but we don't have licenses. We need proper licenses for everyone on the team to be compliant. So my suggestion is to look elsewhere.

To be honest I think OneNote is fine, except there is no way to notify on Slack when changes are made. GH wiki has the notifications, but is more hassle to use.

**Comment by aronhoyer** [comment]
my main gripes with onenote is its lack of a comment feature (which for me is pretty deal breaking) and no `<pre>` or `<code>` styles.

but if notion is a no-go because of licensing, i'd cast my vote for confluence, even though i try to avoid atlassian products.

**Comment by aronhoyer** [comment]
my main gripes with onenote is its lack of a comment feature (which for me is pretty deal breaking) and no `<pre>` or `<code>` styles.

but if notion is a no-go because of licensing, i'd cast my vote for confluence, even though i try to avoid atlassian products.

**Comment by nilsml** [comment]
Let's keep our eyes up for wiki app candidates. Closing this one as it is for the content and not the tool
