### ISSUE TITLE
Enable OAuth proxy in Radix

### ISSUE THREAD

**Issue by nilsml** [equinor/data-marketplace#139]
**In order to make authentication more stable, we will try enabling OAuth proxy in Radix**
Might fix #125
Might fix #142 
Also addressing #129

## Acceptance criteria
- User is logged in with her Equinor credentials in SSO fashion

## Sub-tasks

- [x] Configure app registration in Azure
- [ ] Have Datacatalog team or some admin give consent to our app
- [x] Add oauth config to radixconfig file
- [x] Create new branch to be deployed to test environment
- [ ] Make changes to code for using the proxy (remove OAuth2 stuff basically)

**Comment by nilsml** [comment]
For now we get only 500 from nginx, so need to investigate.

**Comment by nilsml** [comment]
500 issue fixed. Stops because of admin concent noe. Possibly because we need some approvals from Data Catalog team 🤔

**Comment by aronhoyer** [comment]
@nilsml you had some stuff you wanted to document here before closing, no?

**Comment by nilsml** [comment]
We can leave it for now. We have tried out the OAuth proxy, but it makes it harder for the developers to make things work locally. Also a bit less control on what's happening. Will have a look at NextAuth instead.
