### ISSUE TITLE
Send checkout data to Collibra

### ISSUE THREAD

**Issue by aronhoyer** [equinor/data-marketplace#190]
**In order to trigger the request access workflow in Collibra, we need to send data to Collibra to instantiate the workflow and add the required user provided data**

---

# Todo
- [x] Investigate workflow `POST` request schema
- [x] Get workflow ID for request access workflow from Collibra (see comment on #161)
- [x] Get user ID (Collibra user ID) of the currently signed in user
- [x] Implement `POST` request to send checkout data and instantiate workflow
