### ISSUE TITLE
Set up hosting

### ISSUE THREAD

**Issue by nilsml** [equinor/data-marketplace#56]
## Todos

- [x] Talk with the Raidx team about setup with internal network
- [ ] Set up application in Radix
- [x] Define AD group(s) for application
- [x] Create new internal repository for radix config

## Acceptance criteria
* PR's merged to main are automatically deployed to production environment
* Production environment is reachable for people on the internal network
* Users need to authenticate to be able to use the app

**Comment by nilsml** [comment]
It is not possible to talk with the intranet from Radix. Looking into if AccessIT is exposed to the outside by some API.

**Comment by nilsml** [comment]
https://github.com/equinor/accessit-api/wiki

**Comment by nilsml** [comment]
Picking up this again. Will look into possibilities of running the main app in Radix, and have a proxy in Azure for connecting to AccessIT.

**Comment by nilsml** [comment]
They are planning on exposing the API through APIM around September, which means it will be available to us in Radix.
Suggest we set up Radix then and mock the API for now.

FYI:


![Image](https://user-images.githubusercontent.com/1836295/181193954-d77a6f5e-72f4-48c2-a1c0-48c214421316.png)
